// Auto-generated from categories.json — do not hand-edit. See categories.json for the source list.
export default [
  "Advocacy",
  "Arts",
  "Arts & Culture",
  "Business",
  "Childcare",
  "Community",
  "Disability Services",
  "Economic Development",
  "Education",
  "Education & Training",
  "Environment",
  "Environmental",
  "Government",
  "Health",
  "Housing",
  "Legal",
  "Mental Health",
  "Non-Profit",
  "Not-For-Profit",
  "Other",
  "Peer Support",
  "Research",
  "Science",
  "Senior Services",
  "Social Services",
  "Support Group",
  "Technology"
];
